src/objects/TestCObj__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>s_No__c</fullName>
        <label>s No</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>TestCObj</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TestCObjs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/apexTest.cls
public  class apexTest {
    String hellou=' anil HellowHow r u';
    
   public  Account a =new Account (Name='IBM', Industry='Tech');
    
   public Contact cobj=new Contact(FirstName='Anil',LastName='mahanta',Email='demo@gmail.com');
   public  list<Account> listAccount=[select Name,Type,Industry from Account];
    
  //  public list<TestCObj__c testcobj{get;set;}
    
   //testcobj =select s_No__c from TestCObj__c;
   

 //   TestCObj__c TestCObj__cObj
  /* public list<TestCObj__c> gettestcobj()
    {
    	return testcobj;
    	
    }*/
    
 public String gethellou()
{
	System.debug('Hello');
	
	
return hellou;
}

public list<Account> getlistAccount()
{
	return listAccount;
}
public Account geta()
{
	return a;
}

public Contact getcobj()
{
	return cobj;
}

}